#!/bin/sh

set -eu

AIRCONNECT_DIR="/var/packages/AirConnect/target"

logfile=/tmp/aircast.log

start_aircast ()
{
    ip="$1"
    echo "[$(date +'%T')] Starting aircast on ${ip}" >> ${logfile}

    su airconnect -s /bin/sh -c "${AIRCONNECT_DIR}/aircast -b ${ip} -z -f ${logfile} -d all=error -d main=info" >> ${logfile} 2>&1

    cnt=0
    while [ $cnt -lt 3 ]; do
        if grep -q "adding renderer" ${logfile}; then
            return 0
        fi
        cnt=$((cnt + 1))
        sleep 1
    done
    return 1
}

start_airconnect ()
{
    rm -f "${logfile}"
    touch "${logfile}"
    chown airconnect:users "${logfile}"

    # If you want to start the aircast process on a specific IP please uncomment the following lines
    # and set your own local IP address:
    #
    # start_aircast "1.2.3.4" || true
    # return  0

    interfaces=$(ifconfig -a | grep 'Ethernet' -A 1 | grep -E 'inet (addr:)?(192\.168\.|10\.)' -B 1 | grep 'Ethernet' | grep -v "lbr0" | cut -d ' ' -f 1)

    if [ -z "$interfaces" ]; then
        echo "Failed to get local Ethernet interfaces" > "${SYNOPKG_TEMP_LOGFILE}"
        exit 1
    fi

    # Try lbr0 interface first if exists
    interfaces="lbr0 $interfaces"

    for interface in $interfaces; do
        ip=$(/sbin/ifconfig "$interface" | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')
        if [ -n "$ip" ]; then
            if start_aircast "$ip"; then
                return 0
            else
                killall -15 aircast
            fi
        fi
    done

    echo "Failed to start aircast on any of the local interfaces, please make sure you have at least one UPnP/Sonos device on your network" > "${SYNOPKG_TEMP_LOGFILE}"
    exit 1
}

stop_airconnect ()
{
    killall -15 aircast
}

airconnect_status ()
{
    # Check if ps has ax options
    if ps ax >/dev/null 2>&1; then
        # shellcheck disable=SC2009
        if ! ps ax | grep aircast | grep -v -q grep; then
            return 1
        fi
    else
        # shellcheck disable=SC2009
        if ! ps | grep aircast | grep -v -q grep; then
            return 1
        fi
    fi

    return 0
}

case $1 in
    start)
        echo Starting AirConnect ...
        start_airconnect
        exit $?
        ;;
    stop)
        echo Stopping AirConnect ...
        stop_airconnect
        exit $?
        ;;
    status)
        if airconnect_status
        then
            echo AirConnect is running
            exit 0
        else
            echo AirConnect is not running
            exit 1
        fi
        ;;
    log)
        echo "/tmp/aircast.log"
        exit 0
        ;;
    *)
        exit 1
        ;;
esac
